services:
  # ====================================
  # 2. Кэш и Очереди (Redis)
  # ====================================
  redis:
    image: redis:7-alpine
    container_name: rpg-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # ====================================
  # 3. Твой Бэкенд
  # ====================================
  rpg-library:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpg-library-v2
    ports:
      - "80:3000"
    volumes:
      - ./games:/games
    # Подключаем наш файл с секретами
    env_file:
      - .env
    # Эти переменные перекроют те, что в .env (если есть совпадения)
    environment:
      - GAMES_DIR=/games
      - NODE_ENV=production
    restart: unless-stopped
    # Говорим Докеру: "Не запускай бэкенд, пока не поднимутся базы!"
    depends_on:
      - redis

# Объявляем жесткий диск для базы данных
volumes:
  pg_data: