# docker-compose.dev.yml (Локальная разработка)
services:
  rpg-library:
    # Заставляем сервер автоматически перезагружаться при изменениях
    command: nodemon server.js
    volumes:
      # Прокидываем всю папку src разом (там лежат db, routes, services)
      - ./api/src:/app/api/src
      # Главный файл сервера
      - ./api/server.js:/app/api/server.js
      # Ювелирно прокидываем только один скрипт из папки public
      - ./api/public/rpg-fixes.js:/app/api/public/rpg-fixes.js
      
    restart: "no"
    environment:
      - NODE_ENV=development