name: Deploy to Home Server

on:
  workflow_run:
    workflows: ["Node.js CI"] # Запускать только после успешных тестов
    types:
      - completed

jobs:
  deploy:
    name: Auto Deploy
    # Проверяем, что тесты прошли успешно (зеленая галочка)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    defaults:
      run:
        # ИСПРАВЛЕНО: Добавлен слеш в начале, чтобы путь был абсолютным
        working-directory: /root/rpgm
        
    steps:
    - name: Получение свежего кода с GitHub
      run: git pull origin main

    - name: Перезапуск Docker
      run: |
        # Включаем современный параллельный сборщик для скорости
        export DOCKER_BUILDKIT=1
        
        # 1. Собираем новый образ в фоне (сайт в это время РАБОТАЕТ)
        docker compose build
        
        # 2. Мгновенно перезапускаем контейнер (downtime ~2 секунды) и удаляем старые хвосты
        docker compose up -d --remove-orphans