name: Node.js CI

on:
  push:
    branches: [ "main" ] # Запускает пайплайн при прямом пуше
  pull_request:
    branches: [ "main" ] # Проверяет код ДО слияния чужих веток

jobs:
  build-and-test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
    - name: Скачивание кода
      uses: actions/checkout@v4

    - name: Настройка Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Установка пакетов (Strict Mode)
      working-directory: ./api
      run: npm ci

    - name: Запуск тестов
      working-directory: ./api
      env:
        REDIS_URL: redis://localhost:6379
      run: npm test
      
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Скачивание кода
      uses: actions/checkout@v4

    - name: Настройка Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Установка пакетов (Strict Mode)
      working-directory: ./frontend
      run: npm ci

    - name: Сборка фронтенда
      working-directory: ./frontend
      run: npm run build
      
